[package]
name = "gravsim"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bytemuck = "1.24.0"
env_logger = "0.11.8"
imgui = "0.12.0"
imgui-wgpu = "0.25.0"
imgui-winit-support = "0.13.0"
log = "0.4.28"
pollster = "0.4.0"
wgpu = "25.0.0"
winit = "0.30.12"
